config/routes.rb
Rails.application.routes.draw do
  devise_for :employees

  namespace :employees do
    resources :lists
  end

end

app/models/employee.rb
class Employee < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :lists
end

app/models/list.rb
class List < ActiveRecord::Base
  belongs_to :employee
  has_many :tasks

  has_many :incomplete_tasks, ->{where(completed_at: nil)}, class_name: "Task"

  accepts_nested_attributes_for :tasks, reject_if: :all_blank, allow_destroy: true
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :list
  validates :name, presence: true

  def completed?
    completed_at.present?
  end

  def completed=(value)
    puts value
    self[:completed_at] = Time.now() if value == "1"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/employees/application_controller.rb
class Employees::ApplicationController < ApplicationController
  before_action :authenticate_employee!
end

app/controllers/employees/lists_controller.rb
class Employees::ListsController < Employees::ApplicationController

  def new
    new_list
  end

  def create
    new_list(list_params)
    if new_list.save
      redirect_to [:employees, @list]
    else
      render :new
    end
  end

  def edit
    list
  end

  def update
    if list.update_attributes(list_params)
      redirect_to [:employees, list]
    else
      puts list.errors.full_messages
      render :show
    end
  end

  def show
    list
  end


private

  def list_params
    @list_params ||= params.require(:list).permit(:name,
      tasks_attributes: [:id, :name, :completed, :_destroy])
  end

  def list
    @list ||= current_employee.lists.find(params[:id])
  end

  def new_list(attrs={})
    @list ||= current_employee.lists.build(attrs)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/employees/lists/_form.html.erb
<%= simple_form_for [:employees, @list] do |f| %>
  <%= f.input :name %>
  <div id="tasks">
    <%= f.simple_fields_for :tasks do |task| %>
      <%= render 'task_fields', f: task %>
    <% end %>
    <div class="links">
      <%= link_to_add_association 'add task', f, :tasks %>
    </div>
  </div>


  <%= f.submit 'Save' %>

<% end %>

app/views/employees/lists/_task_fields.html.erb
<div class="nested-fields">
  <%= f.input :name %>
  <%= f.input :completed?, :as => :boolean %>
  <%= link_to_remove_association "delete task", f %>
</div>

app/views/employees/lists/_task_item.html.erb
<%= simple_form_for [:employees, @list] do |f| %>

  <div id="tasks">
    <%= f.simple_fields_for :tasks,@list.tasks.build do |task| %>
      <%= render 'task_fields', f: task %>
    <% end %>
    <div class="links">
      <%= link_to_add_association 'add task', f, :tasks %>
    </div>
  </div>


  <%= f.submit 'Save' %>

<% end %>

app/views/employees/lists/edit.html.erb
<h2>Edit List</h2>
<%= render 'form' %>

app/views/employees/lists/new.html.erb
<h1>New List</h1>
<%= render 'form' %>

app/views/employees/lists/show.html.erb
<h1><%= @list.name %></h1>
<div class="meta">Created by <%= @list.employee.name %></div>
<%= link_to "edit", edit_employees_list_path(@list) %>
<ul class="tasks">
  <% @list.incomplete_tasks.each do |task| %>
    <li><%= check_box_tag :completed?, false %> <%= task.name %></li>
  <% end %>
</ul>

<h1>Edit List</h1>
<%= render 'task_item' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ToDo</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

  <%= javascript_include_tag 'application' %>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
</body>
</html>